const AssetsManifestPlugin = require('webpack-assets-manifest');

const { integrityHashAlgorithms } = require('../constants');

/**
 * Setup AssetsManifestPlugin
 * @return {Object} AssetsManifestPlugin
 */
module.exports = () => ({
  plugins: [
    // generates a json file that matches the original filenames with the hashed versions
    new AssetsManifestPlugin({
      // defines assets manifest file name
      output: 'assets-manifest.json',
      // includes SRI hashes generated by SubresourceIntegrityPlugin
      integrity: true,
      // defines hash algorithms to use when generating SRI
      integrityHashes: integrityHashAlgorithms,
    }),
  ],
});
