const AssetsManifestPlugin = require('webpack-assets-manifest');

const { INTEGRITY_HASH_ALGORITHMS } = require('../constants');

/**
 * Setup AssetsManifestPlugin
 * @return {Object} AssetsManifestPlugin
 */
module.exports = () => ({
  plugins: [
    // generates a json file that matches the original filenames with the hashed versions
    new AssetsManifestPlugin({
      output: 'assets-manifest.json',
      // includes SRI hashes generated by SubresourceIntegrityPlugin
      integrity: true,
      // hash algorithms to use when generating SRI
      integrityHashes: INTEGRITY_HASH_ALGORITHMS,
    }),
  ],
});
